### ISSUE TITLE
Develop a protocol for client-server communication

### ISSUE THREAD

**Issue by A-GigaC** [trunk-monorepo-vcs/vcs#1]

**Comment by A-GigaC** [comment]
### Basic info

- protocol uses tcp-sockets
- 1b = 1 byte
- every request from client to server will use first byte of the package for indicate the request type, there is the list of requests with numbers:
1. establish connection
2. get dirr structure
3. get stat (info about file)
4. get file 
5. and others..
### Protocol description

#### Establish connection with server:
client REQUESTS server => {
1b: request type = 1,
4b: tokenLength (или если это хеш какой-то, то мы знаем длину?),
nb: token as string
}

server RESPONSES client => {
8b: package size,
1b: connection status (0 on success and 1 for exceptions)
}

_On success, server sets current position at the root of the dirr_

#### READ_DIR structure
client REQUESTS server => {
1b: request type = 2 (READ_DIR),
4b: path length,
nb: path as string
}

server RESPONSES client => {
1b: 1 if error, 0 - succes
if success:
  4b: names [of dirrs and files] count,
  for each {names count} of names ->
    1b: name length,
    nb: name
if error:
  4b: error string length,
  nb: error string
}

#### READ (file) - calls when the file doesnt exists on your local, but exists on the remote
client REQUESTS server => {
1b: request type = 4, (READ)
4b: filename length,
nb: filename
}

server RESPONS client => {
8b: package size,
1b: status = 0 on succes and 1 if error,
on success:
  8bytes: filelength,
  nb: file bin content
on error:
  4b: error message length,
  nb: error message string
}

**perhaps, in the process, this scheme will be supplemented and overgrown with new requests**

**Comment by AnarCom** [comment]
1) create connection should use token (not password and login) + response of server MUST contain error message
2) read_dir should contain folder path in request and maybe it should return metadata of file and folder in response 
3) i think that it could be much better if all of events should contain paths (and server should be stateless as much as possible)

**Comment by AnarCom** [comment]
i think that is could be better if you use **_protobuf_** for protocol specification (due to different endians in some cpu architectures)

**Comment by AnarCom** [comment]
https://conan.io/
